# Generated by Django 4.0.4 on 2022-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='text_password',
            field=models.CharField(max_length=50),
        ),
    ]
