# Generated by Django 4.0.4 on 2022-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_texts_text1_texts_text2_texts_text3_texts_text4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='text_password',
            field=models.CharField(max_length=100),
        ),
    ]
