# Generated by Django 4.0.4 on 2022-05-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_texts_text_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text9',
            field=models.TextField(blank=True, default=''),
        ),
    ]
